# Generated by Django 4.2.2 on 2023-07-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_department_title_alter_userinfo_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=32, verbose_name='Mobile')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], default=1, verbose_name='Level')),
                ('status', models.SmallIntegerField(choices=[(1, 'occupied'), (2, 'available')], default=2, verbose_name='Status')),
            ],
        ),
    ]
