# Generated by Django 4.2.2 on 2023-07-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_boss_alter_userinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('logo', models.FileField(max_length=128, upload_to='city', verbose_name='Logo')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '男'), (1, '女')], verbose_name='性别'),
        ),
    ]
